# Start with the golang image
FROM golang:1.20

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Download and install any required Go modules
RUN go mod tidy

# Build the Go app
RUN go build -o sub sub.go

# Command to run the executable
CMD ["./sub"]
